FROM node:20-alpine AS build
WORKDIR /app

COPY package*.json ./
COPY frontend/package*.json ./frontend/
RUN npm install

COPY frontend ./frontend
WORKDIR /app/frontend
RUN npm run build:prod

FROM nginx:1.27-alpine
COPY frontend/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/frontend/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
